alphabet = 'abcdefghijklmnopqrstuvwxyz'
def runningKey(ciphertext,key):
 plainText = ''
 for i in range(len(ciphertext)):
     p = alphabet.index(ciphertext[i])
     k = alphabet.index(key[i%len(key)])
     c = (p - k) % 26
     plainText += alphabet[c]
 return plainText

# # From NCC 2010 6B cipher
# cipherText = "jVGRWVIVDEYLWIBEKFVKOSFFYEDCFXHQZWBBGGRKFKMYGBOYCQGGWQXJVRSSPMQHSMXVALNWFRUGEMDELHEDSSBUAEPNYQBBQUJDSYIZWZXUCYMHGUDPNICLTUHXBAMPRJWMZWPWKIAMLMLBPROTVLVTIXWUXDYFHVTDLHNZPVWDGRPCZAUPGGABKHMETVSLSZMMSIFILHOENJKWODAIUNYZNXUTDTTIYNCPDAGKHSIENAZTUIMTZIBXKVOZKCXUXJTSPLMWYLVFMQJXUIYMZXEWJGHHKMIGRXYEFLOAOHRQWPRFFLHZEB"
# key = "BENTDOUBLELIKEOLDBEGGARSUNDERSACKSKNOCKKNEEDCOUGHINGLIKEHAGSWECURSEDTHROUGHSLUDGETILLONTHEHAUNTINGFLARESWETURNEDOURBACKSANDTOWARDSOURDISTANTRESTBEGANTOTRUDGEMENMARCHEDASLEEPMANYHADLOSTTHEIRBOOTSBUTLIMPEDONBLOODSHODALLWENTLAMEALLBLINDDRUNKWITHFATIGUEDEAFEVENTOTHEHOOTSOFTIREDOUTSTRIPPEDFIVENINESTHATDROPPEDBEHIND"
# 
# print(runningKey(cipherText.lower(), key.lower()))
